//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Studio.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDM_CTXT_DLGVIEW                101
#define IDD_DASMGOTODIALOG              103
#define IDR_MAINFRAME                   128
#define IDS_RESOURCE_NO_NONDEFAULT_STRINGTABLE_VIEW 129
#define IDS_STRVIEW_HEAD_ID             130
#define IDS_FORMAT_RESTREE_RESIDSTRING  131
#define IDS_FORMAT_RESTREE_RESNAMEDOBJ  132
#define IDI_FOLDERC                     132
#define IDS_FORMAT_RESTREE_RESOBJ       133
#define IDI_FOLDERO                     133
#define IDS_FORMAT_RESTREE_STRINGTABLE  134
#define IDI_DOC                         134
#define IDS_ERROR_STRINGTABLE_LOAD      135
#define IDI_ITEMERROR                   135
#define IDS_FORMAT_RESDOCTITLE          136
#define IDD_DLGPROPERTIES               136
#define IDS_CTXT_MNU_PROPERTIES         137
#define IDM_CTXT_RESVIEW                137
#define IDS_FORMAT_DASM_ENTRYPOINT      137
#define IDS_CTXT_MNU_VIEW               138
#define IDR_DASMTYPE                    138
#define IDS_CTXT_MNU_VIEW_BYTE          139
#define IDM_CTXT_HEXVIEW                139
#define IDS_FORMAT_DASM_NICE_TITLE      139
#define IDS_CTXT_MNU_VIEW_DWORD         140
#define IDD_CHOOSEVIEWER                140
#define IDS_DASM_COULD_NOT_DASM         140
#define IDS_CTXT_MNU_VIEW_HEX           141
#define IDS_DASM_SUCCESSFUL_DASM        141
#define IDS_CTXT_MNU_VIEW_WORD          142
#define IDD_DASMCALLSTACK               142
#define IDS_FORMAT_IMPEXP_EXP_FORWARDER 142
#define IDR_WORKSPACE_RESOURCES         143
#define IDB_UP                          143
#define IDB_DOWN                        144
#define IDS_FORMAT_IMPEXP_EXP_NORMAL    144
#define IDS_IMPEXP_EXPBYNAME_ROOT       145
#define IDS_IMPEXP_EXPBYORD_ROOT        146
#define IDS_IMPEXP_FMT_MODNAME          147
#define IDS_IMPEXP_IMPORT_READERROR     148
#define IDS_IMPEXP_FMT_ORDINALIMP_ONLY  149
#define IDS_IMPEXP_IMPBYNAME_ROOT       150
#define IDS_IMPEXP_IMPBYORD_ROOT        151
#define IDS_IMPEXP_FMT_ORDINALEXP_ONLY  152
#define IDS_DELAYLOADROOTNAME           152
#define IDS_IMPEXP_EXPORT_READERROR     153
#define IDS_IMPORTROOTNAME              154
#define IDS_EXPORTROOTNAME              155
#define IDR_WORKSPACE_IMPEXP            156
#define IDS_SETRESPARAMS_ERROR_UNKNOWN  157
#define IDS_MAINFRAME_TITLE_CLOSED      158
#define IDS_MAINFRAME_TITLE_OPEN        159
#define IDS_FILE_OPEN_WORKSPACE_TITLE   160
#define IDS_STRVIEW_HEAD_STRING         161
#define IDS_VERVIEW_HEAD_FIELD          162
#define IDS_VERVIEW_HEAD_VALUE          163
#define IDS_ERROR_MENU_EXTENDED         164
#define IDS_ICONVIEW_FORMAT_DEVICE_IMAGE 165
#define IDS_ICONVIEW_CURSOR_HOTSPOT     166
#define IDS_DLGVIEW_DLGPROP_STR         167
#define IDS_DLGVIEW_CTRLPROP_STR        168
#define IDS_DLGVIEW_PREDEF_CLASS_LISTBOX 169
#define IDS_DLGVIEW_PREDEF_CLASS_BUTTON 170
#define IDS_DLGVIEW_PREDEF_CLASS_EDIT   171
#define IDS_DLGVIEW_PREDEF_CLASS_STATIC 172
#define IDS_DLGVIEW_PREDEF_CLASS_SCROLLBAR 173
#define IDS_DLGVIEW_PREDEF_CLASS_COMBOBOX 174
#define IDS_ERROR_DLG_FAIL              175
#define IDS_ERROR_BITMAP_LOAD           176
#define IDS_ACCEL_ASCII_CTRL            177
#define IDS_ACCEL_CTRL_PLUS             178
#define IDS_ACCEL_ALT_PLUS              179
#define IDS_ACCEL_SHIFT_PLUS            180
#define IDS_ACCEL_HEAD_ID               181
#define IDS_ACCEL_HEAD_KEY              182
#define IDR_ACCELTYPE                   183
#define IDR_BITMAPTYPE                  184
#define IDR_ICONTYPE                    185
#define IDR_HEXTYPE                     186
#define IDR_DIALOGTYPE                  187
#define IDR_MENUTYPE                    188
#define IDR_STRINGTABLETYPE             189
#define IDR_VERSIONTYPE                 190
#define IDM_CTXT_RESTREEVIEW            191
#define IDS_IMPEXP_TLB_ROOT             191
#define IDR_WORKSPACE_DASM              192
#define IDR_BITMAPTYPE1                 193
#define IDS_GLOBAL_VIEW_BAR_CAPTION     193
#define IDD_ICONFRAMEHEAD               198
#define IDD_DASMCALLSTACK1              199
#define IDD_GLOBAL_VIEW_PANE            199
#define IDC_LBSTYLES                    1000
#define IDC_LBEXSTYLES                  1001
#define IDC_EDCONTROL                   1002
#define IDC_CMBDEV                      1003
#define IDC_STHOTSPOT                   1004
#define IDC_LBVIEWERS                   1006
#define IDC_CALLSTACK                   1007
#define IDC_BACKUP                      1008
#define IDC_CMBADDRESS                  1009
#define ID_VIEW_WORKSPACE               32771
#define ID_VIEW_RAWRESOURCES            32772
#define ID_FILE_EXECUTE                 32774
#define ID_FILE_CLOSEALLWINDOWS         32775
#define ID_FILE_CLOSE_WORKSPACE         32776
#define ID_FILE_OPEN_WORKSPACE          32777
#define ID_CTXT_VIEWHEX                 32778
#define ID_CTXT_HEXVIEW_VIEWBYTE        32781
#define ID_CTXT_HEXVIEW_VIEWWORD        32782
#define ID_CTXT_HEXVIEW_VIEWDWORD       32783
#define ID_CTXT_DLGVIEW_PROPERTIES      32784
#define ID_CTXT_VIEW                    32785
#define ID_WINDOW_NEW_WINDOW            32786
#define ID_WINDOW_TILE                  32787
#define ID_WINDOW_ARRANGE_ICONS         32788
#define ID_CTXT_VIEWWITH                32789
#define ID_DASM_GOTO                    32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
