/*******************************************************************/
/* (c) Copyright 2004 - - Mark McGuill. All Rights Reserved.       */
/*                                                                 */
/* File: insturctions.h                                            */
/* Owner: Mark McGuill                                             */
/* Create Date: 09/Sep/2004										   */
/*                                                                 */
/* Purpose: Contains all instructions tables and related structs,  */
/*			enums etc											   */
/*                                                                 */
/* Comments: File is fully ANSI C compliant, should compile under  */
/*           Windows, Linux, BSD etc, tested with VC, GCC, CC      */
/*                                                                 */
/*                                                                 */
/* Modified:                                                       */
/*                                                                 */
/*                                                                 */
/*******************************************************************/

typedef enum tagAddressingMethodEnum
{
	amNone, amA, amC, amD, amE, amF, amG, amI, amJ, amM, amO, amP,amQ,
	amR, amS, amT, amV, amW, amX, amY, amHardCodeReg, amHardCodeNum,
	amFloatingPoint, amHardCodeFPStackReg,
}AddressingMethodEnum;

/*******************************************************************/

/*  CInstructionStream::krgszHardCodeRegOperand[] depends on order 
	of this enum, careful */

typedef enum tagOperandTypeEnum
{
	otRegAL,
	otRegCL,
	otRegDL,
	otRegBL,
	otRegAH,
	otRegCH,
	otRegDH,
	otRegBH,
	otRegAX,
	otRegDX,
	otRegFS,
	otRegGS,
	otRegES,
	otRegCS,
	otRegSS,
	otRegDS,
	otRegeAX,
	otRegeDX,
	otRegeSP,
	otRegeCX,
	otRegeBX,
	otRegeBP,
	otRegeSI,
	otRegeDI,
	otRegEAX,
	otRegEDX,
	otRegESP,
	otRegECX,
	otRegEBX,
	otRegEBP,
	otRegESI,
	otRegEDI,
	otFP_ST0,
	otFP_ST1,
	otFP_ST2,
	otFP_ST3,
	otFP_ST4,
	otFP_ST5,
	otFP_ST6,
	otFP_ST7,
	otRegNone, /* TODO: Used?? */
	otNone,    
	ota,
	otb,
	otc,
	otd,
	otdq,
	otp,
	otpi,
	otps,
	otq,
	ots,
	otss,
	otsi,
	otv,
	otw,
	otHard_1,
	otpd,
	otsd,
	otFP_SingleReal,
	otFP_1428B,
	otFP_2B,
	otFP_DwordInteger,
	otFP_ExtendedReal,
	otFP_DoubleReal,
	otFP_98108B,
	otFP_WordInteger,
	otFP_PackedBCD,
	otFP_QwordInteger,
}OperandTypeEnum;

/*******************************************************************/

typedef enum tagOperandFormatDecoration 
{
	opfdNone,
	opfdSizePrefix,		/*  prefix byte, word, dword */
	opfdPtrSizePrefix,	/*  prefix byte ptr, word ptr, dword ptr */
}OperandFormatDecoration ;

/*******************************************************************/

typedef enum tagInstructionFormatDependancy
{
	ifdNone,
	ifdOperSizeLookupNeeded,
	ifdAddrSizeLookupNeeded,
	ifdPrefixLookupNeeded,
	ifdModEqual3LookupNeeded,/*  this is not the same as extension */
							 /*  opcode lookup. couple of  */
							 /*  instructions, clflush, sfence,  */
							 /*  lfence, mfence. 0x0F->Group 16-> */
							 /*  clflush/sfence depends on  */
							 /*  mod being 3 or not */
}InstructionFormatDependancy;

/*******************************************************************/

typedef struct tagTABLE_OPERAND
{
	AddressingMethodEnum AddressingMethod;
	OperandTypeEnum Type;
	OperandFormatDecoration dec;
}TABLE_OPERAND, *PTABLE_OPERAND;

/*******************************************************************/

typedef struct tagTABLE_INSTRUCTION
{
	MnemonicEnum Mnemonic;
	LPCSTR lpszMne;						/*  <= remove once  */
										/*  finished testing */
	TABLE_OPERAND Operand[MAX_OPERANDS];
	ULONG cOperands;
	InstructionFormatDependancy ifd;
	ProcessorTypeEnum proc_type;
}TABLE_INSTRUCTION, *PTABLE_INSTRUCTION;

/*******************************************************************/

typedef struct tagOPER_SIZE_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION ti16bit;
	TABLE_INSTRUCTION ti32bit;
}OPER_SIZE_DEP_INS_ENTRY,*POPER_SIZE_DEP_INS_ENTRY;

/*******************************************************************/

typedef struct tagADDR_SIZE_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION ti16bit;
	TABLE_INSTRUCTION ti32bit;
}ADDR_SIZE_DEP_INS_ENTRY,*PADDR_SIZE_DEP_INS_ENTRY;

/*******************************************************************/

typedef struct tagMOD_IS_3_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION tiModIs3;
	TABLE_INSTRUCTION tiModIsNot3;
}MOD_IS_3_DEP_INS_ENTRY,*PMOD_IS_3_DEP_INS_ENTRY;

/*******************************************************************/

typedef struct tagPREFIX_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION tiNoPrefix;
	TABLE_INSTRUCTION ti66;
	TABLE_INSTRUCTION tiF2;
	TABLE_INSTRUCTION tiF3;
}PREFIX_DEP_INS_ENTRY,*PPREFIX_DEP_INS_ENTRY;

/*******************************************************************/

#define SIZEOF_TABLE(x) (sizeof(x) / sizeof(x[0]))

/*******************************************************************/

#define OPERAND_ENTRY(x,y) x,y,opfdNone
#define OPERAND_ENTRY_DEC(x,y,z) x,y,z

#define UsePrevious	OPERAND_ENTRY(amNone,otNone)
#define Eb	OPERAND_ENTRY(amE,otb)
#define Ed	OPERAND_ENTRY(amE,otd)
#define Ev	OPERAND_ENTRY(amE,otv)
#define Gb	OPERAND_ENTRY(amG,otb)
#define Gd	OPERAND_ENTRY(amG,otd)
#define Gv	OPERAND_ENTRY(amG,otv)
#define Ew	OPERAND_ENTRY(amE,otw)
#define Gw	OPERAND_ENTRY(amG,otw)
#define Ma	OPERAND_ENTRY(amM,ota)
#define Ib	OPERAND_ENTRY(amI,otb)
#define Iv	OPERAND_ENTRY(amI,otv)
#define Jb	OPERAND_ENTRY(amJ,otb)
#define Jv	OPERAND_ENTRY(amJ,otv)
#define Yv	OPERAND_ENTRY(amY,otv)
#define Xv	OPERAND_ENTRY(amX,otv)
#define Ap	OPERAND_ENTRY(amA,otp)
#define Sw	OPERAND_ENTRY(amS,otw)
#define Mv	OPERAND_ENTRY(amM,otv)
#define Ob	OPERAND_ENTRY(amO,otb)
#define Ov	OPERAND_ENTRY(amO,otv)
#define Yb	OPERAND_ENTRY(amY,otb)
#define Xb	OPERAND_ENTRY(amX,otb)
#define Iw	OPERAND_ENTRY(amI,otw)
#define Mp	OPERAND_ENTRY(amM,otp)
#define Mq	OPERAND_ENTRY(amM,otq)
#define Ep	OPERAND_ENTRY(amE,otp)
#define Ms	OPERAND_ENTRY(amM,ots)
#define Mb	OPERAND_ENTRY(amM,otb)

#define Rd	OPERAND_ENTRY(amR,otd)
#define Cd  OPERAND_ENTRY(amC,otd)
#define Dd  OPERAND_ENTRY(amD,otd)
#define Td  OPERAND_ENTRY(amT,otd)

#define Pd  OPERAND_ENTRY(amP,otd)
#define Pq  OPERAND_ENTRY(amP,otq)
#define Qq  OPERAND_ENTRY(amQ,otq)

#define Pdq	OPERAND_ENTRY(amP,otdq)
#define Vdq	OPERAND_ENTRY(amV,otdq)
#define Wdq	OPERAND_ENTRY(amW,otdq)
#define Qdq	OPERAND_ENTRY(amQ,otdq)
#define Vq OPERAND_ENTRY(amV,otq)
#define Wq 	OPERAND_ENTRY(amW,otq)
#define Vps	OPERAND_ENTRY(amV,otps)

#define Vss	OPERAND_ENTRY(amV,otss)
#define Vpd	OPERAND_ENTRY(amV,otpd)
#define Vsd	OPERAND_ENTRY(amV,otsd)

#define Ws  OPERAND_ENTRY(amW,ots)
#define Wps OPERAND_ENTRY(amW,otps)
#define Wss OPERAND_ENTRY(amW,otss)
#define Wpd OPERAND_ENTRY(amW,otpd)
#define Wsd OPERAND_ENTRY(amW,otsd)

#define Ppi	OPERAND_ENTRY(amP,otpi)


#define FPSR	OPERAND_ENTRY(amFloatingPoint,otFP_SingleReal)
#define FP1428	OPERAND_ENTRY(amFloatingPoint,otFP_1428B)
#define FPDI	OPERAND_ENTRY(amFloatingPoint,otFP_DwordInteger)
#define FPER	OPERAND_ENTRY(amFloatingPoint,otFP_ExtendedReal)
#define FPDR	OPERAND_ENTRY(amFloatingPoint,otFP_DoubleReal)
#define FP98108	OPERAND_ENTRY(amFloatingPoint,otFP_98108B)
#define FP2		OPERAND_ENTRY(amFloatingPoint,otFP_2B)
#define FPWI	OPERAND_ENTRY(amFloatingPoint,otFP_WordInteger)
#define FPPBCD	OPERAND_ENTRY(amFloatingPoint,otFP_PackedBCD)
#define FPQI	OPERAND_ENTRY(amFloatingPoint,otFP_QwordInteger)

#define opNone OPERAND_ENTRY(amNone,otNone)

#define EbWithPtrSizePrefix OPERAND_ENTRY_DEC(amE,otb,opfdPtrSizePrefix)
#define EwWithPtrSizePrefix OPERAND_ENTRY_DEC(amE,otw,opfdPtrSizePrefix)
#define EdWithPtrSizePrefix OPERAND_ENTRY_DEC(amE,otd,opfdPtrSizePrefix)
#define EvWithPtrSizePrefix OPERAND_ENTRY_DEC(amE,otv,opfdPtrSizePrefix)
#define EpWithPtrSizePrefix OPERAND_ENTRY_DEC(amE,otp,opfdPtrSizePrefix)
#define MbWithPtrSizePrefix OPERAND_ENTRY_DEC(amM,otb,opfdPtrSizePrefix)
#define MdWithPtrSizePrefix OPERAND_ENTRY_DEC(amM,otd,opfdPtrSizePrefix)
#define MqWithPtrSizePrefix OPERAND_ENTRY_DEC(amM,otq,opfdPtrSizePrefix)
#define MsWithPtrSizePrefix OPERAND_ENTRY_DEC(amM,ots,opfdPtrSizePrefix)
#define MpWithPtrSizePrefix OPERAND_ENTRY_DEC(amM,otp,opfdPtrSizePrefix)
#define QdWithPtrSizePrefix OPERAND_ENTRY_DEC(amQ,otd,opfdPtrSizePrefix)
#define QqWithPtrSizePrefix OPERAND_ENTRY_DEC(amQ,otq,opfdPtrSizePrefix)
#define QdqWithPtrSizePrefix OPERAND_ENTRY_DEC(amQ,otdq,opfdPtrSizePrefix)
#define WdqWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otdq,opfdPtrSizePrefix)
#define WpsWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otps,opfdPtrSizePrefix)
#define WssWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otss,opfdPtrSizePrefix)
#define WpdWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otpd,opfdPtrSizePrefix)
#define WsdWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otsd,opfdPtrSizePrefix)
#define WdWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otd,opfdPtrSizePrefix)
#define WqWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,otq,opfdPtrSizePrefix)
#define WsWithPtrSizePrefix OPERAND_ENTRY_DEC(amW,ots,opfdPtrSizePrefix)
#define IbWithSizePrefix	OPERAND_ENTRY_DEC(amI,otb,opfdSizePrefix)
#define QpiWithPtrSizePrefix OPERAND_ENTRY_DEC(amQ,otpi,opfdSizePrefix)

#define AL	OPERAND_ENTRY(amHardCodeReg,otRegAL)
#define CL	OPERAND_ENTRY(amHardCodeReg,otRegCL)
#define DL	OPERAND_ENTRY(amHardCodeReg,otRegDL)
#define BL	OPERAND_ENTRY(amHardCodeReg,otRegBL)
#define AH	OPERAND_ENTRY(amHardCodeReg,otRegAH)
#define CH	OPERAND_ENTRY(amHardCodeReg,otRegCH)
#define DH	OPERAND_ENTRY(amHardCodeReg,otRegDH)
#define BH	OPERAND_ENTRY(amHardCodeReg,otRegBH)

#define AX	OPERAND_ENTRY(amHardCodeReg,otRegAX)
#define DX	OPERAND_ENTRY(amHardCodeReg,otRegDX)
#define ES	OPERAND_ENTRY(amHardCodeReg,otRegES)
#define CS	OPERAND_ENTRY(amHardCodeReg,otRegCS)
#define FS	OPERAND_ENTRY(amHardCodeReg,otRegFS)
#define GS	OPERAND_ENTRY(amHardCodeReg,otRegGS)
#define SS	OPERAND_ENTRY(amHardCodeReg,otRegSS)
#define DS	OPERAND_ENTRY(amHardCodeReg,otRegDS)

#define eCX OPERAND_ENTRY(amHardCodeReg,otRegeCX)
#define eSP OPERAND_ENTRY(amHardCodeReg,otRegeSP)
#define eAX	OPERAND_ENTRY(amHardCodeReg,otRegeAX)
#define eBX	OPERAND_ENTRY(amHardCodeReg,otRegeBX)
#define eDX	OPERAND_ENTRY(amHardCodeReg,otRegeDX)
#define eDI	OPERAND_ENTRY(amHardCodeReg,otRegeDI)
#define eSI OPERAND_ENTRY(amHardCodeReg,otRegeSI)
#define eBP OPERAND_ENTRY(amHardCodeReg,otRegeBP)

#define EAX OPERAND_ENTRY(amHardCodeReg,otRegEAX)
#define ECX OPERAND_ENTRY(amHardCodeReg,otRegECX)
#define EDX	OPERAND_ENTRY(amHardCodeReg,otRegEDX)
#define EBX	OPERAND_ENTRY(amHardCodeReg,otRegEBX)
#define ESP	OPERAND_ENTRY(amHardCodeReg,otRegESP)
#define EBP	OPERAND_ENTRY(amHardCodeReg,otRegEBP)
#define ESI OPERAND_ENTRY(amHardCodeReg,otRegESI)
#define EDI OPERAND_ENTRY(amHardCodeReg,otRegEDI)

#define ST0 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST0)
#define ST1 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST1)
#define ST2 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST2)
#define ST3 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST3)
#define ST4 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST4)
#define ST5 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST5)
#define ST6 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST6)
#define ST7 OPERAND_ENTRY(amHardCodeFPStackReg, otFP_ST7)

#define HARD_1 OPERAND_ENTRY(amHardCodeNum,otHard_1)

/*******************************************************************/

/*  Standard Instruction Def Macros */

#define INSTRUCTION_ENTRY_BLANK()	\
	{MneNone,"!!None!!",opNone,opNone,opNone,0,ifdNone,ptNone},
#define INSTRUCTION_ENTRY0(t)		\
	{Mne##t,#t,opNone,opNone,opNone,0,ifdNone,ptNone},
#define INSTRUCTION_ENTRY1(t,u) 	\
	{Mne##t,#t,u,opNone,opNone,1,ifdNone,ptNone},
#define INSTRUCTION_ENTRY2(t,u,v)	\
	{Mne##t,#t,u,v,opNone,2,ifdNone,ptNone},
#define INSTRUCTION_ENTRY3(t,u,v,w)	\
	{Mne##t,#t,u,v,w,3,ifdNone,ptNone},

/*  Explicit Mnemonic String Macros */

#define INSTRUCTION_ENTRY0_SZ(t,u)		\
	{Mne##t,#u,opNone,opNone,opNone,0,ifdNone,ptNone},

#define INSTRUCTION_ENTRY1_SZ(t,u,v) {Mne##t,#u,v,opNone,opNone,1,ifdNone,ptNone},
#define INSTRUCTION_ENTRY2_SZ(t,u,v,w)	{Mne##t,#u,v,w,opNone,2,ifdNone,ptNone},
#define INSTRUCTION_ENTRY3_SZ(t,u,v,w,x) {Mne##t,#u,v,w,x,3,ifdNone,ptNone},

/*  Some Instructions need extra lookups depending on addr size,  */
/*  oper size or prefix. These macros make it a little more  */
/*  readable below */

#define INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(t)	\
	{Mne##t,#t,opNone,opNone,opNone,0,ifdOperSizeLookupNeeded,ptNone},

#define INSTRUCTION_ENTRY1_ADDR_SIZE_LOOKUP(t,u) \
	{Mne##t,#t,u,opNone,opNone,1,ifdAddrSizeLookupNeeded,ptNone},

#define INSTRUCTION_ENTRY0_MOD_LOOKUP_NEEDED(t) \
	{Mne##t,#t,opNone,opNone,opNone,0,ifdModEqual3LookupNeeded,ptNone},

#define INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(t) \
	{Mne##t,#t,opNone,opNone,opNone,0,ifdPrefixLookupNeeded,ptNone},

/*******************************************************************/

#define BEGIN_INSTRUCTION_TABLE(x) static TABLE_INSTRUCTION x = {		
#define END_INSTRUCTION_TABLE };
#define BEGIN_INSTRUCTION_ROW(x) {
#define END_INSTRUCTION_ROW(x) },

/*******************************************************************/

BEGIN_INSTRUCTION_TABLE(gtab1ByteInstructions[0x10][0x10])
	BEGIN_INSTRUCTION_ROW(0x00)
		INSTRUCTION_ENTRY2(Add,Eb,Gb)
		INSTRUCTION_ENTRY2(Add,Ev,Gv)
		INSTRUCTION_ENTRY2(Add,Gb,Eb)
		INSTRUCTION_ENTRY2(Add,Gv,Ev)
		INSTRUCTION_ENTRY2(Add,AL,Ib)
		INSTRUCTION_ENTRY2(Add,eAX,Iv)
		INSTRUCTION_ENTRY1(Push,ES)
		INSTRUCTION_ENTRY1(Pop,ES)
		INSTRUCTION_ENTRY2(Or,Eb,Gb)
		INSTRUCTION_ENTRY2(Or,Ev,Gv)
		INSTRUCTION_ENTRY2(Or,Gb,Eb)
		INSTRUCTION_ENTRY2(Or,Gv,Ev)
		INSTRUCTION_ENTRY2(Or,AL,Ib)
		INSTRUCTION_ENTRY2(Or,eAX,Iv)
		INSTRUCTION_ENTRY1(Push,CS)
		INSTRUCTION_ENTRY_BLANK()/*  <== 2  Byte Opcode Escape Sequence 0x0F */
	END_INSTRUCTION_ROW(0x00)

	BEGIN_INSTRUCTION_ROW(0x01)
		INSTRUCTION_ENTRY2(Adc,Eb,Gb)
		INSTRUCTION_ENTRY2(Adc,Ev,Gv)
		INSTRUCTION_ENTRY2(Adc,Gb,Eb)
		INSTRUCTION_ENTRY2(Adc,Gv,Ev)
		INSTRUCTION_ENTRY2(Adc,AL,Ib)
		INSTRUCTION_ENTRY2(Adc,eAX,Iv)
		INSTRUCTION_ENTRY1(Push,SS)
		INSTRUCTION_ENTRY1(Pop,SS)
		INSTRUCTION_ENTRY2(Sbb,Eb,Gb)
		INSTRUCTION_ENTRY2(Sbb,Ev,Gv)
		INSTRUCTION_ENTRY2(Sbb,Gb,Eb)
		INSTRUCTION_ENTRY2(Sbb,Gv,Ev)
		INSTRUCTION_ENTRY2(Sbb,AL,Ib)
		INSTRUCTION_ENTRY2(Sbb,eAX,Iv)
		INSTRUCTION_ENTRY1(Push,DS)
		INSTRUCTION_ENTRY1(Pop,DS)
	END_INSTRUCTION_ROW(0x01)
	
	BEGIN_INSTRUCTION_ROW(0x02)
		INSTRUCTION_ENTRY2(And,Eb,Gb)
		INSTRUCTION_ENTRY2(And,Ev,Gv)
		INSTRUCTION_ENTRY2(And,Gb,Eb)
		INSTRUCTION_ENTRY2(And,Gv,Ev)
		INSTRUCTION_ENTRY2(And,AL,Ib)
		INSTRUCTION_ENTRY2(And,eAX,Iv)
		INSTRUCTION_ENTRY_BLANK()/*  <== ES Segment Select Prefix */
		INSTRUCTION_ENTRY0(Daa)
		INSTRUCTION_ENTRY2(Sub,Eb,Gb)
		INSTRUCTION_ENTRY2(Sub,Ev,Gv)
		INSTRUCTION_ENTRY2(Sub,Gb,Eb)
		INSTRUCTION_ENTRY2(Sub,Gv,Ev)
		INSTRUCTION_ENTRY2(Sub,AL,Ib)
		INSTRUCTION_ENTRY2(Sub,eAX,Iv)
		INSTRUCTION_ENTRY_BLANK()/*  <== CS Segment Select Prefix */
		INSTRUCTION_ENTRY0(Das)
	END_INSTRUCTION_ROW(0x02)
	
	BEGIN_INSTRUCTION_ROW(0x03)
		INSTRUCTION_ENTRY2(Xor,Eb,Gb)
		INSTRUCTION_ENTRY2(Xor,Ev,Gv)
		INSTRUCTION_ENTRY2(Xor,Gb,Eb)
		INSTRUCTION_ENTRY2(Xor,Gv,Ev)
		INSTRUCTION_ENTRY2(Xor,AL,Ib)
		INSTRUCTION_ENTRY2(Xor,eAX,Iv)
		INSTRUCTION_ENTRY_BLANK()/*  <== SS Segment Select Prefix */
		INSTRUCTION_ENTRY0(Aaa)
		INSTRUCTION_ENTRY2(Cmp,Eb,Gb)
		INSTRUCTION_ENTRY2(Cmp,Ev,Gv)
		INSTRUCTION_ENTRY2(Cmp,Gb,Eb)
		INSTRUCTION_ENTRY2(Cmp,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmp,AL,Ib)
		INSTRUCTION_ENTRY2(Cmp,eAX,Iv)
		INSTRUCTION_ENTRY_BLANK()/*  <== DS Segment Select Prefix*/
		INSTRUCTION_ENTRY0(Aas)
	END_INSTRUCTION_ROW(0x03)

	BEGIN_INSTRUCTION_ROW(0x04)
		INSTRUCTION_ENTRY1(Inc,eAX)
		INSTRUCTION_ENTRY1(Inc,eCX)
		INSTRUCTION_ENTRY1(Inc,eDX)
		INSTRUCTION_ENTRY1(Inc,eBX)
		INSTRUCTION_ENTRY1(Inc,eSP)
		INSTRUCTION_ENTRY1(Inc,eBP)
		INSTRUCTION_ENTRY1(Inc,eSI)
		INSTRUCTION_ENTRY1(Inc,eDI)
		INSTRUCTION_ENTRY1(Dec,eAX)
		INSTRUCTION_ENTRY1(Dec,eCX)
		INSTRUCTION_ENTRY1(Dec,eDX)
		INSTRUCTION_ENTRY1(Dec,eBX)
		INSTRUCTION_ENTRY1(Dec,eSP)
		INSTRUCTION_ENTRY1(Dec,eBP)
		INSTRUCTION_ENTRY1(Dec,eSI)
		INSTRUCTION_ENTRY1(Dec,eDI)
	END_INSTRUCTION_ROW(0x04)

	BEGIN_INSTRUCTION_ROW(0x05)
		INSTRUCTION_ENTRY1(Push,eAX)
		INSTRUCTION_ENTRY1(Push,eCX)
		INSTRUCTION_ENTRY1(Push,eDX)
		INSTRUCTION_ENTRY1(Push,eBX)
		INSTRUCTION_ENTRY1(Push,eSP)
		INSTRUCTION_ENTRY1(Push,eBP)
		INSTRUCTION_ENTRY1(Push,eSI)
		INSTRUCTION_ENTRY1(Push,eDI)
		INSTRUCTION_ENTRY1(Pop,eAX)
		INSTRUCTION_ENTRY1(Pop,eCX)
		INSTRUCTION_ENTRY1(Pop,eDX)
		INSTRUCTION_ENTRY1(Pop,eBX)
		INSTRUCTION_ENTRY1(Pop,eSP)
		INSTRUCTION_ENTRY1(Pop,eBP)
		INSTRUCTION_ENTRY1(Pop,eSI)
		INSTRUCTION_ENTRY1(Pop,eDI)
	END_INSTRUCTION_ROW(0x05)

	BEGIN_INSTRUCTION_ROW(0x06)
		INSTRUCTION_ENTRY0(Pusha)
		INSTRUCTION_ENTRY0(Popa)
		INSTRUCTION_ENTRY2(Bound,Gv,Mv)
		INSTRUCTION_ENTRY2(Arpl,Ew,Gw)
		INSTRUCTION_ENTRY_BLANK()			/*  <== FS Segment Select Prefix */
		INSTRUCTION_ENTRY_BLANK()			/*  <== GS Segment Select Prefix */
		INSTRUCTION_ENTRY_BLANK()			/*  <== Operand Size Prefix */
		INSTRUCTION_ENTRY_BLANK()			/*  <== Address Size Prefix */
		INSTRUCTION_ENTRY1(Push,Iv)
		INSTRUCTION_ENTRY3(Imul,Gv,Ev,Iv)
		INSTRUCTION_ENTRY1(Push,Ib)
		INSTRUCTION_ENTRY3(Imul,Gv,Ev,Ib)
		INSTRUCTION_ENTRY2(Ins,AL,DX)		
		INSTRUCTION_ENTRY2(Ins,eAX,DX)
		INSTRUCTION_ENTRY2(Outs,DX,AL)		
		INSTRUCTION_ENTRY2(Outs,DX,eAX)
	END_INSTRUCTION_ROW(0x06)

	BEGIN_INSTRUCTION_ROW(0x07)
		INSTRUCTION_ENTRY1(Jo,Jb)
		INSTRUCTION_ENTRY1(Jno,Jb)
		INSTRUCTION_ENTRY1(Jb,Jb)
		INSTRUCTION_ENTRY1(Jnb,Jb)
		INSTRUCTION_ENTRY1(Jz,Jb)
		INSTRUCTION_ENTRY1(Jnz,Jb)
		INSTRUCTION_ENTRY1(Jbe,Jb)
		INSTRUCTION_ENTRY1(Ja,Jb)
		INSTRUCTION_ENTRY1(Js,Jb)
		INSTRUCTION_ENTRY1(Jns,Jb)
		INSTRUCTION_ENTRY1(Jp,Jb)
		INSTRUCTION_ENTRY1(Jnp,Jb)
		INSTRUCTION_ENTRY1(Jl,Jb)
		INSTRUCTION_ENTRY1(Jge,Jb)
		INSTRUCTION_ENTRY1(Jle,Jb)
		INSTRUCTION_ENTRY1(Jg,Jb)
	END_INSTRUCTION_ROW(0x07)

	BEGIN_INSTRUCTION_ROW(0x08)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,Iv)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,IbWithSizePrefix)
		INSTRUCTION_ENTRY2(Test,Eb,Gb)
		INSTRUCTION_ENTRY2(Test,Ev,Gv)
		INSTRUCTION_ENTRY2(Xchg,Eb,Gb)
		INSTRUCTION_ENTRY2(Xchg,Ev,Gv)
		INSTRUCTION_ENTRY2(Mov,EbWithPtrSizePrefix,Gb)
		INSTRUCTION_ENTRY2(Mov,EvWithPtrSizePrefix,Gv)
		INSTRUCTION_ENTRY2(Mov,Gb,Eb)
		INSTRUCTION_ENTRY2(Mov,Gv,Ev)
		INSTRUCTION_ENTRY2(Mov,EwWithPtrSizePrefix,Sw)
		INSTRUCTION_ENTRY2(Lea,Gv,Mv)
		INSTRUCTION_ENTRY2(Mov,Sw,Ew)
		INSTRUCTION_ENTRY1(Pop,EvWithPtrSizePrefix)
	END_INSTRUCTION_ROW(0x08)

	BEGIN_INSTRUCTION_ROW(0x09)
		INSTRUCTION_ENTRY0(Nop)
		INSTRUCTION_ENTRY2(Xchg,eAX,eCX)
		INSTRUCTION_ENTRY2(Xchg,eAX,eDX)
		INSTRUCTION_ENTRY2(Xchg,eAX,eBX)
		INSTRUCTION_ENTRY2(Xchg,eAX,eSP)
		INSTRUCTION_ENTRY2(Xchg,eAX,eBP)
		INSTRUCTION_ENTRY2(Xchg,eAX,eSI)
		INSTRUCTION_ENTRY2(Xchg,eAX,eDI)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(CbwOperSizeDep)	
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(CwdOperSizeDep)
		INSTRUCTION_ENTRY1(Call,Ap)
		INSTRUCTION_ENTRY0(Wait)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(PushfOperSizeDep)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(PopfOperSizeDep)
		INSTRUCTION_ENTRY0(Sahf)
		INSTRUCTION_ENTRY0(Lahf)
	END_INSTRUCTION_ROW(0x09)
	
	BEGIN_INSTRUCTION_ROW(0x0A)
		INSTRUCTION_ENTRY2(Mov,AL,Ob)
		INSTRUCTION_ENTRY2(Mov,eAX,Ov)
		INSTRUCTION_ENTRY2(Mov,Ob,AL)
		INSTRUCTION_ENTRY2(Mov,Ov,eAX)
		INSTRUCTION_ENTRY0_SZ(Movs,movsb)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(MovsOperSizeDep)
		INSTRUCTION_ENTRY0_SZ(Cmps,cmpsb)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(CmpsOperSizeDep)
		INSTRUCTION_ENTRY2(Test,AL,Ib)
		INSTRUCTION_ENTRY2(Test,eAX,Iv)
		INSTRUCTION_ENTRY0_SZ(Stos,stosb)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(StosOperSizeDep)
		INSTRUCTION_ENTRY0_SZ(Lods,lodsb)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(LodsOperSizeDep)
		INSTRUCTION_ENTRY0_SZ(Scas,scasb)
		INSTRUCTION_ENTRY0_OP_SIZE_LOOKUP(ScasOperSizeDep)
	END_INSTRUCTION_ROW(0x0A)
	
	BEGIN_INSTRUCTION_ROW(0x0B)
		INSTRUCTION_ENTRY2(Mov,AL,Ib)
		INSTRUCTION_ENTRY2(Mov,CL,Ib)
		INSTRUCTION_ENTRY2(Mov,DL,Ib)
		INSTRUCTION_ENTRY2(Mov,BL,Ib)
		INSTRUCTION_ENTRY2(Mov,AH,Ib)
		INSTRUCTION_ENTRY2(Mov,CH,Ib)
		INSTRUCTION_ENTRY2(Mov,DH,Ib)
		INSTRUCTION_ENTRY2(Mov,BH,Ib)
		INSTRUCTION_ENTRY2(Mov,eAX,Iv)
		INSTRUCTION_ENTRY2(Mov,eCX,Iv)
		INSTRUCTION_ENTRY2(Mov,eDX,Iv)
		INSTRUCTION_ENTRY2(Mov,eBX,Iv)
		INSTRUCTION_ENTRY2(Mov,eSP,Iv)
		INSTRUCTION_ENTRY2(Mov,eBP,Iv)
		INSTRUCTION_ENTRY2(Mov,eSI,Iv)
		INSTRUCTION_ENTRY2(Mov,eDI,Iv)
	END_INSTRUCTION_ROW(0x0B)

	BEGIN_INSTRUCTION_ROW(0x0C)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY1(Ret,Iw)
		INSTRUCTION_ENTRY0(Ret)
		INSTRUCTION_ENTRY2(Les,Gv,Mp)
		INSTRUCTION_ENTRY2(Lds,Gv,Mp)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,Iv)
		INSTRUCTION_ENTRY2(Enter,Iw,Ib)
		INSTRUCTION_ENTRY0(Leave)
		INSTRUCTION_ENTRY1(Ret,Iw)
		INSTRUCTION_ENTRY0(Ret)
		INSTRUCTION_ENTRY0(Int3)
		INSTRUCTION_ENTRY1(Int,Ib)
		INSTRUCTION_ENTRY0(Into)
		INSTRUCTION_ENTRY0(Iret)
	END_INSTRUCTION_ROW(0x0C)

	BEGIN_INSTRUCTION_ROW(0x0D)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,HARD_1)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,HARD_1)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,CL)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,CL)
		INSTRUCTION_ENTRY1(Aam,Ib)
		INSTRUCTION_ENTRY1(Aad,Ib)
		INSTRUCTION_ENTRY_BLANK()			
		INSTRUCTION_ENTRY0(Xlatb)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
		INSTRUCTION_ENTRY0(FloatEsc)
	END_INSTRUCTION_ROW(0x0D)

	BEGIN_INSTRUCTION_ROW(0x0E)
		INSTRUCTION_ENTRY1(Loopne,Jb)
		INSTRUCTION_ENTRY1(Loope,Jb)
		INSTRUCTION_ENTRY1(Loop,Jb)
		INSTRUCTION_ENTRY1_ADDR_SIZE_LOOKUP(JcxzAddrSizeDep,Jb)
		INSTRUCTION_ENTRY2(In,AL,Ib)
		INSTRUCTION_ENTRY2(In,eAX,Ib)
		INSTRUCTION_ENTRY2(Out,Ib,AL)
		INSTRUCTION_ENTRY2(Out,Ib,eAX)
		INSTRUCTION_ENTRY1(Call,Jv)
		INSTRUCTION_ENTRY1(Jmp,Jv)
		INSTRUCTION_ENTRY1(Jmp,Ap)
		INSTRUCTION_ENTRY1(Jmp,Jb)
		INSTRUCTION_ENTRY2(In,AL,DX)
		INSTRUCTION_ENTRY2(In,eAX,DX)
		INSTRUCTION_ENTRY2(Out,DX,AL)
		INSTRUCTION_ENTRY2(Out,DX,eAX)
	END_INSTRUCTION_ROW(0x0E)

	BEGIN_INSTRUCTION_ROW(0x0F)
		INSTRUCTION_ENTRY_BLANK()	/*  <== LOCK Prefix */
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()	/*  <== REPNE Prefix */
		INSTRUCTION_ENTRY_BLANK()	/*  <== REP Prefix */
		INSTRUCTION_ENTRY0(Hlt)
		INSTRUCTION_ENTRY0(Cmc)
		INSTRUCTION_ENTRY2(None,EbWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,Iv)
		INSTRUCTION_ENTRY0(Clc)
		INSTRUCTION_ENTRY0(Stc)
		INSTRUCTION_ENTRY0(Cli)
		INSTRUCTION_ENTRY0(Sti)
		INSTRUCTION_ENTRY0(Cld)
		INSTRUCTION_ENTRY0(Std)
		INSTRUCTION_ENTRY0(None)
		INSTRUCTION_ENTRY0(None)
	END_INSTRUCTION_ROW(0x0F)
END_INSTRUCTION_TABLE

/*******************************************************************/
/*******************************************************************/
/*******************************************************************/

BEGIN_INSTRUCTION_TABLE(gtab2ByteInstructions[0x10][0x10])
	BEGIN_INSTRUCTION_ROW(0x00)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY2(Lar,Gv,Ew)
		INSTRUCTION_ENTRY2(Lsl,Gv,Ew)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0(Clts)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0(Invd)
		INSTRUCTION_ENTRY0(Wbinvd)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x00)

	BEGIN_INSTRUCTION_ROW(0x01)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F10)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F11)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F12)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F13)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F14)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F15)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F16)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F17)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x01)

	BEGIN_INSTRUCTION_ROW(0x02)
		INSTRUCTION_ENTRY2(Mov,Rd,Cd)
		INSTRUCTION_ENTRY2(Mov,Rd,Dd)
		INSTRUCTION_ENTRY2(Mov,Cd,Rd)
		INSTRUCTION_ENTRY2(Mov,Dd,Rd)
		INSTRUCTION_ENTRY2(Mov,Rd,Td)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY2(Mov,Td,Rd)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F28)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F29)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F2A)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F2B)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F2C)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F2D)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F2E)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F2F)
	END_INSTRUCTION_ROW(0x02)

	BEGIN_INSTRUCTION_ROW(0x03)
		INSTRUCTION_ENTRY0(Wrmsr)
		INSTRUCTION_ENTRY0(Rdtsc)
		INSTRUCTION_ENTRY0(Rdmsr)
		INSTRUCTION_ENTRY0(Rdpmc)
		INSTRUCTION_ENTRY0(Sysenter)
		INSTRUCTION_ENTRY0(Sysexit)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x03)

	BEGIN_INSTRUCTION_ROW(0x04)
		INSTRUCTION_ENTRY2(Cmovo,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovno,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovb,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovnb,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovz,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovnz,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovbe,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmova,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovs,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovns,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovp,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovnp,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovl,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovge,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovle,Gv,Ev)
		INSTRUCTION_ENTRY2(Cmovg,Gv,Ev)
	END_INSTRUCTION_ROW(0x04)

	BEGIN_INSTRUCTION_ROW(0x05)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F50)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F51)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F52)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F53)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F54)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F55)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F56)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F57)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F58)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F59)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F5A)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F5B)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F5C)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F5D)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F5E)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F5F)
	END_INSTRUCTION_ROW(0x05)

	BEGIN_INSTRUCTION_ROW(0x06)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F60)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F61)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F62)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F63)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F64)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F65)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F66)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F67)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F68)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F69)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F6A)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F6B)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F6C)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F6D)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F6E)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F6F)
	END_INSTRUCTION_ROW(0x06)

	BEGIN_INSTRUCTION_ROW(0x07)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F70)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F71)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F72)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F73)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F74)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F75)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F76)
		INSTRUCTION_ENTRY0(Emms)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F7E)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F7F)
	END_INSTRUCTION_ROW(0x07)

	BEGIN_INSTRUCTION_ROW(0x08)
		INSTRUCTION_ENTRY1(Jo,Jv)
		INSTRUCTION_ENTRY1(Jno,Jv)
		INSTRUCTION_ENTRY1(Jb,Jv)
		INSTRUCTION_ENTRY1(Jnb,Jv)
		INSTRUCTION_ENTRY1(Jz,Jv)
		INSTRUCTION_ENTRY1(Jnz,Jv)
		INSTRUCTION_ENTRY1(Jbe,Jv)
		INSTRUCTION_ENTRY1(Ja,Jv)
		INSTRUCTION_ENTRY1(Js,Jv)
		INSTRUCTION_ENTRY1(Jns,Jv)
		INSTRUCTION_ENTRY1(Jp,Jv)
		INSTRUCTION_ENTRY1(Jnp,Jv)
		INSTRUCTION_ENTRY1(Jl,Jv)
		INSTRUCTION_ENTRY1(Jge,Jv)
		INSTRUCTION_ENTRY1(Jle,Jv)
		INSTRUCTION_ENTRY1(Jg,Jv)
	END_INSTRUCTION_ROW(0x08)

	BEGIN_INSTRUCTION_ROW(0x09)
		INSTRUCTION_ENTRY1(Seto,Eb)
		INSTRUCTION_ENTRY1(Setno,Eb)
		INSTRUCTION_ENTRY1(Setb,Eb)
		INSTRUCTION_ENTRY1(Setnb,Eb)
		INSTRUCTION_ENTRY1(Setz,Eb)
		INSTRUCTION_ENTRY1(Setnz,Eb)
		INSTRUCTION_ENTRY1(Setbe,Eb)
		INSTRUCTION_ENTRY1(Seta,Eb)
		INSTRUCTION_ENTRY1(Sets,Eb)
		INSTRUCTION_ENTRY1(Setns,Eb)
		INSTRUCTION_ENTRY1(Setp,Eb)
		INSTRUCTION_ENTRY1(Setnp,Eb)
		INSTRUCTION_ENTRY1(Setl,Eb)
		INSTRUCTION_ENTRY1(Setge,Eb)
		INSTRUCTION_ENTRY1(Setle,Eb)
		INSTRUCTION_ENTRY1(Setg,Eb)
	END_INSTRUCTION_ROW(0x09)

	BEGIN_INSTRUCTION_ROW(0x0A)
		INSTRUCTION_ENTRY1(Push,FS)
		INSTRUCTION_ENTRY1(Pop,FS)
		INSTRUCTION_ENTRY0(Cpuid)
		INSTRUCTION_ENTRY2(Bt,Ev,Gv)
		INSTRUCTION_ENTRY3(Shld,EvWithPtrSizePrefix,Gv,Ib)
		INSTRUCTION_ENTRY3(Shld,EvWithPtrSizePrefix,Gv,CL)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Push,GS)
		INSTRUCTION_ENTRY1(Pop,GS)
		INSTRUCTION_ENTRY0(Rsm)
		INSTRUCTION_ENTRY2(Bts,Ev,Gv)
		INSTRUCTION_ENTRY3(Shrd,EvWithPtrSizePrefix,Gv,Ib)
		INSTRUCTION_ENTRY3(Shrd,EvWithPtrSizePrefix,Gv,CL)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY2(Imul,Gv,Ev)
	END_INSTRUCTION_ROW(0x0A)

	BEGIN_INSTRUCTION_ROW(0x0B)
		INSTRUCTION_ENTRY2(Cmpxchg,Eb,Gb)
		INSTRUCTION_ENTRY2(Cmpxchg,Ev,Gv)
		INSTRUCTION_ENTRY2(Lss,Gv,Mp)
		INSTRUCTION_ENTRY2(Btr,Ev,Gv)
		INSTRUCTION_ENTRY2(Lfs,Gv,Mp)
		INSTRUCTION_ENTRY2(Lgs,Gv,Mp)
		INSTRUCTION_ENTRY2(Movzx,Gv,EbWithPtrSizePrefix)
		INSTRUCTION_ENTRY2(Movzx,Gv,EwWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY2(None,EvWithPtrSizePrefix,Ib)
		INSTRUCTION_ENTRY2(Btc,Ev,Gv)
		INSTRUCTION_ENTRY2(Bsf,Gv,Ev)
		INSTRUCTION_ENTRY2(Bsr,Gv,Ev)
		INSTRUCTION_ENTRY2(Movsx,Gv,EbWithPtrSizePrefix)
		INSTRUCTION_ENTRY2(Movsx,Gv,EwWithPtrSizePrefix)
	END_INSTRUCTION_ROW(0x0B)

	BEGIN_INSTRUCTION_ROW(0x0C)
		INSTRUCTION_ENTRY2(Xadd,Eb,Gb)
		INSTRUCTION_ENTRY2(Xadd,Ev,Gv)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FC2)
		INSTRUCTION_ENTRY2(Movnti,Ed,Gd)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FC4)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FC5)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FC6)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Bswap,EAX)
		INSTRUCTION_ENTRY1(Bswap,ECX)
		INSTRUCTION_ENTRY1(Bswap,EDX)
		INSTRUCTION_ENTRY1(Bswap,EBX)
		INSTRUCTION_ENTRY1(Bswap,ESP)
		INSTRUCTION_ENTRY1(Bswap,EBP)
		INSTRUCTION_ENTRY1(Bswap,ESI)
		INSTRUCTION_ENTRY1(Bswap,EDI)
	END_INSTRUCTION_ROW(0x0C)

	BEGIN_INSTRUCTION_ROW(0x0D)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD1)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD2)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD3)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD4)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD5)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD6)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD7)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD8)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FD9)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FDA)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FDB)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FDC)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FDD)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FDE)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FDF)
	END_INSTRUCTION_ROW(0x0D)

	BEGIN_INSTRUCTION_ROW(0x0E)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE0)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE1)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE2)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE3)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE4)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE5)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE6)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE7)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE8)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FE9)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FEA)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FEB)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FEC)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FED)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FEE)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FEF)
	END_INSTRUCTION_ROW(0x0E)

	BEGIN_INSTRUCTION_ROW(0x0F)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF1)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF2)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF3)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF4)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF5)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF6)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF7)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF8)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FF9)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FFA)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FFB)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FFC)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FFD)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0FFE)
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x0F)
END_INSTRUCTION_TABLE


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


BEGIN_INSTRUCTION_TABLE(gtabExtensionInstructions[0x10][0x08])
	BEGIN_INSTRUCTION_ROW(0x00)
		INSTRUCTION_ENTRY2(Add,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Or,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Adc,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Sbb,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(And,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Sub,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Xor,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Cmp,UsePrevious,UsePrevious)
	END_INSTRUCTION_ROW(0x00)

	BEGIN_INSTRUCTION_ROW(0x01)
		INSTRUCTION_ENTRY2(Rol,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Ror,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Rcl,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Rcr,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Shl,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Shr,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY2(Sar,UsePrevious,UsePrevious)
	END_INSTRUCTION_ROW(0x01)

	BEGIN_INSTRUCTION_ROW(0x02)
		INSTRUCTION_ENTRY2(Test,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Not,UsePrevious)
		INSTRUCTION_ENTRY1(Neg,UsePrevious)
		INSTRUCTION_ENTRY1(Mul,UsePrevious)
		INSTRUCTION_ENTRY1(Imul,UsePrevious)
		INSTRUCTION_ENTRY1(Div,UsePrevious)
		INSTRUCTION_ENTRY1(Idiv,UsePrevious)
	END_INSTRUCTION_ROW(0x02)

	BEGIN_INSTRUCTION_ROW(0x03)
		INSTRUCTION_ENTRY1(Inc,EbWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Dec,EbWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x03)

	BEGIN_INSTRUCTION_ROW(0x04)
		INSTRUCTION_ENTRY1(Inc,EvWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Dec,EvWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Call,EvWithPtrSizePrefix)
		// Do nmot know how to disassemble these two my self yet
		INSTRUCTION_ENTRY_BLANK() //INSTRUCTION_ENTRY1(Callf,EpWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Jmp,EvWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK() //INSTRUCTION_ENTRY1(Jmpf,EpWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Push,EvWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x04)

	BEGIN_INSTRUCTION_ROW(0x05)
		INSTRUCTION_ENTRY1(Sldt,Ew)
		INSTRUCTION_ENTRY1(Str,Ev)
		INSTRUCTION_ENTRY1(Lldt,Ew)
		INSTRUCTION_ENTRY1(Ltr,Ew)
		INSTRUCTION_ENTRY1(Verr,Ew)
		INSTRUCTION_ENTRY1(Verw,Ew)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x05)

	BEGIN_INSTRUCTION_ROW(0x06)
		INSTRUCTION_ENTRY1(Sgdt,MsWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Sidt,MsWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Lgdt,MsWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Lidt,MsWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Smsw,Ew)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Lmsw,Ew)
		INSTRUCTION_ENTRY1(Invlpg,Mb)
	END_INSTRUCTION_ROW(0x06)

	BEGIN_INSTRUCTION_ROW(0x07)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY2(Bt,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Bts,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Btr,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY2(Btc,UsePrevious,UsePrevious)
	END_INSTRUCTION_ROW(0x07)

	BEGIN_INSTRUCTION_ROW(0x08)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Cmpxch8b,MqWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x08)

	BEGIN_INSTRUCTION_ROW(0x09)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x09)

	BEGIN_INSTRUCTION_ROW(0x0A)
		INSTRUCTION_ENTRY2(Mov,UsePrevious,UsePrevious)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x0A)

	BEGIN_INSTRUCTION_ROW(0x0B)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F71_B_2)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F71_B_4)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F71_B_6)
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x0B)

	BEGIN_INSTRUCTION_ROW(0x0C)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F72_C_2)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F72_C_4)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F72_C_6)
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x0C)

	BEGIN_INSTRUCTION_ROW(0x0D)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F73_D_2)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F73_D_3)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F73_D_6)
		INSTRUCTION_ENTRY0_PREFIX_LOOKUP_NEEDED(PrefixDep_0F73_D_7)
	END_INSTRUCTION_ROW(0x0D)

	BEGIN_INSTRUCTION_ROW(0x0E)
		INSTRUCTION_ENTRY1(Fxsave,MdWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Fxrstor,MdWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Ldmxcsr,MdWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Stmxcsr,MdWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY0_MOD_LOOKUP_NEEDED(LFenceModLookup)
		INSTRUCTION_ENTRY0_MOD_LOOKUP_NEEDED(MFenceModLookup)
		INSTRUCTION_ENTRY0_MOD_LOOKUP_NEEDED(SFenceModLookup)
	END_INSTRUCTION_ROW(0x0E)

	BEGIN_INSTRUCTION_ROW(0x0F)
		INSTRUCTION_ENTRY1(Prefetchnta,MbWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Prefetcht0,MbWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Prefetcht1,MbWithPtrSizePrefix)
		INSTRUCTION_ENTRY1(Prefetcht2,MbWithPtrSizePrefix)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY_BLANK()
	END_INSTRUCTION_ROW(0x0F)
END_INSTRUCTION_TABLE


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


BEGIN_INSTRUCTION_TABLE(gtabFPMem[0x08][0x08])
	BEGIN_INSTRUCTION_ROW(0x00) /* D8 */
		INSTRUCTION_ENTRY1(Fadd,FPSR)
		INSTRUCTION_ENTRY1(Fmul,FPSR)
		INSTRUCTION_ENTRY1(Fcom,FPSR)
		INSTRUCTION_ENTRY1(Fcomp,FPSR)
		INSTRUCTION_ENTRY1(Fsub,FPSR)
		INSTRUCTION_ENTRY1(Fsubr,FPSR)
		INSTRUCTION_ENTRY1(Fdiv,FPSR)
		INSTRUCTION_ENTRY1(Fdivr,FPSR)
	END_INSTRUCTION_ROW(0x00)

	BEGIN_INSTRUCTION_ROW(0x01) /* D9 */
		INSTRUCTION_ENTRY1(Fld,FPSR)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fst,FPSR)
		INSTRUCTION_ENTRY1(Fstp,FPSR)
		INSTRUCTION_ENTRY1(Fldenv,FP1428)
		INSTRUCTION_ENTRY1(Fldcw,FP2)
		INSTRUCTION_ENTRY1(Fnstenv,FP1428)
		INSTRUCTION_ENTRY1(Fnstcw,FP2)
	END_INSTRUCTION_ROW(0x01)

	BEGIN_INSTRUCTION_ROW(0x02) /* DA */
		INSTRUCTION_ENTRY1(Fiadd,FPDI)
		INSTRUCTION_ENTRY1(Fimul,FPDI)
		INSTRUCTION_ENTRY1(Ficom,FPDI)
		INSTRUCTION_ENTRY1(Ficomp,FPDI)
		INSTRUCTION_ENTRY1(Fisub,FPDI)
		INSTRUCTION_ENTRY1(Fisubr,FPDI)
		INSTRUCTION_ENTRY1(Fidiv,FPDI)
		INSTRUCTION_ENTRY1(Fidivr,FPDI)
	END_INSTRUCTION_ROW(0x02)
	
	BEGIN_INSTRUCTION_ROW(0x03) /* DB */
		INSTRUCTION_ENTRY1(Fild,FPDI)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fist,FPDI)
		INSTRUCTION_ENTRY1(Fistp,FPDI)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fld,FPER)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fstp,FPER)
	END_INSTRUCTION_ROW(0x03)

	BEGIN_INSTRUCTION_ROW(0x04) /* DC */
		INSTRUCTION_ENTRY1(Fadd,FPDR)
		INSTRUCTION_ENTRY1(Fmul,FPDR)
		INSTRUCTION_ENTRY1(Fcom,FPDR)
		INSTRUCTION_ENTRY1(Fcomp,FPDR)
		INSTRUCTION_ENTRY1(Fsub,FPDR)
		INSTRUCTION_ENTRY1(Fsubr,FPDR)
		INSTRUCTION_ENTRY1(Fdiv,FPDR)
		INSTRUCTION_ENTRY1(Fdivr,FPDR)
	END_INSTRUCTION_ROW(0x04)

	BEGIN_INSTRUCTION_ROW(0x05) /* DD */
		INSTRUCTION_ENTRY1(Fld,FPDR)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fst,FPDR)
		INSTRUCTION_ENTRY1(Fstp,FPDR)
		INSTRUCTION_ENTRY1(Frstor,FP98108)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fnsave,FP98108)
		INSTRUCTION_ENTRY1(Fnstsw,FP2)
	END_INSTRUCTION_ROW(0x05)

	BEGIN_INSTRUCTION_ROW(0x06) /*  DE */
		INSTRUCTION_ENTRY1(Fiadd,FPWI)
		INSTRUCTION_ENTRY1(Fimul,FPWI)
		INSTRUCTION_ENTRY1(Ficom,FPWI)
		INSTRUCTION_ENTRY1(Ficomp,FPWI)
		INSTRUCTION_ENTRY1(Fisub,FPWI)
		INSTRUCTION_ENTRY1(Fisubr,FPWI)
		INSTRUCTION_ENTRY1(Fidiv,FPWI)
		INSTRUCTION_ENTRY1(Fidivr,FPWI)
	END_INSTRUCTION_ROW(0x06)

	BEGIN_INSTRUCTION_ROW(0x07) /*  DF */
		INSTRUCTION_ENTRY1(Fild,FPWI)
		INSTRUCTION_ENTRY_BLANK()
		INSTRUCTION_ENTRY1(Fist,FPWI)
		INSTRUCTION_ENTRY1(Fistp,FPWI)
		INSTRUCTION_ENTRY1(Fbld,FPPBCD)
		INSTRUCTION_ENTRY1(Fild,FPQI)
		INSTRUCTION_ENTRY1(Fbstp,FPPBCD)
		INSTRUCTION_ENTRY1(Fistp,FPQI)
	END_INSTRUCTION_ROW(0x07)
END_INSTRUCTION_TABLE


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


#define FP_8_STD_COLS(x) \
			INSTRUCTION_ENTRY2(x,ST0,ST0) \
			INSTRUCTION_ENTRY2(x,ST0,ST1) \
			INSTRUCTION_ENTRY2(x,ST0,ST2) \
			INSTRUCTION_ENTRY2(x,ST0,ST3) \
			INSTRUCTION_ENTRY2(x,ST0,ST4) \
			INSTRUCTION_ENTRY2(x,ST0,ST5) \
			INSTRUCTION_ENTRY2(x,ST0,ST6) \
			INSTRUCTION_ENTRY2(x,ST0,ST7) \

#define FP_8_REV_COLS(x) \
			INSTRUCTION_ENTRY2(x,ST0,ST0) \
			INSTRUCTION_ENTRY2(x,ST1,ST0) \
			INSTRUCTION_ENTRY2(x,ST2,ST0) \
			INSTRUCTION_ENTRY2(x,ST3,ST0) \
			INSTRUCTION_ENTRY2(x,ST4,ST0) \
			INSTRUCTION_ENTRY2(x,ST5,ST0) \
			INSTRUCTION_ENTRY2(x,ST6,ST0) \
			INSTRUCTION_ENTRY2(x,ST7,ST0) \

#define FP_8_BLANK_COLS() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \
			INSTRUCTION_ENTRY_BLANK() \

#define FP_8_STD_COLS_SINGLE(x) \
			INSTRUCTION_ENTRY1(x,ST0) \
			INSTRUCTION_ENTRY1(x,ST1) \
			INSTRUCTION_ENTRY1(x,ST2) \
			INSTRUCTION_ENTRY1(x,ST3) \
			INSTRUCTION_ENTRY1(x,ST4) \
			INSTRUCTION_ENTRY1(x,ST5) \
			INSTRUCTION_ENTRY1(x,ST6) \
			INSTRUCTION_ENTRY1(x,ST7) \


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


BEGIN_INSTRUCTION_TABLE(gtabFPStackReg[0x8][0x4][0x10])
	BEGIN_INSTRUCTION_ROW(0x00) /*  D8 */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_STD_COLS(Fadd)
			FP_8_STD_COLS(Fmul)
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_STD_COLS(Fcom)
			FP_8_STD_COLS(Fcomp)
		END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			FP_8_STD_COLS(Fsub)
			FP_8_STD_COLS(Fsubr)
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_STD_COLS(Fdiv)
			FP_8_STD_COLS(Fdivr)
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x00)

	BEGIN_INSTRUCTION_ROW(0x01) /*  D9 */
		BEGIN_INSTRUCTION_ROW(0x00) 
			FP_8_STD_COLS(Fld)
			FP_8_STD_COLS(Fxch)
        END_INSTRUCTION_ROW(0x00)
        BEGIN_INSTRUCTION_ROW(0x01)
			INSTRUCTION_ENTRY0(Fnop)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			INSTRUCTION_ENTRY0(Fchs)
			INSTRUCTION_ENTRY0(Fabs)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY0(Ftst)
			INSTRUCTION_ENTRY0(Fxam)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY0(Fld1)
			INSTRUCTION_ENTRY0(Fldl2t)
			INSTRUCTION_ENTRY0(Fldl2e)
			INSTRUCTION_ENTRY0(Fldpi)
			INSTRUCTION_ENTRY0(Fldlg2)
			INSTRUCTION_ENTRY0(Fldln2)
			INSTRUCTION_ENTRY0(Fldz)
			INSTRUCTION_ENTRY_BLANK()
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			INSTRUCTION_ENTRY0(F2xm1)
			INSTRUCTION_ENTRY0(Fyl2x)
			INSTRUCTION_ENTRY0(Fptan)
			INSTRUCTION_ENTRY0(Fpatan)
			INSTRUCTION_ENTRY0(Fxtract)
			INSTRUCTION_ENTRY0(Fprem1)
			INSTRUCTION_ENTRY0(Fdecstp)
			INSTRUCTION_ENTRY0(Fincstp)
			INSTRUCTION_ENTRY0(Fprem)
			INSTRUCTION_ENTRY0(Fyl2xp1)
			INSTRUCTION_ENTRY0(Fsqrt)
			INSTRUCTION_ENTRY0(Fsincos)
			INSTRUCTION_ENTRY0(Frndint)
			INSTRUCTION_ENTRY0(Fscale)
			INSTRUCTION_ENTRY0(Fsin)
			INSTRUCTION_ENTRY0(Fcos)
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x01)

	BEGIN_INSTRUCTION_ROW(0x02) /*  DA */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_STD_COLS(Fcmovb)
			FP_8_STD_COLS(Fcmove)
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_STD_COLS(Fcmovbe)
			FP_8_STD_COLS(Fcmovu)
		END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			FP_8_BLANK_COLS()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY0(Fucompp)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_BLANK_COLS()
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x02)


	BEGIN_INSTRUCTION_ROW(0x03) /*  DB */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_STD_COLS(Fcmovnb)
			FP_8_STD_COLS(Fcmovne)
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_STD_COLS(Fcmovnbe)
			FP_8_STD_COLS(Fcmovnu)
        END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY0(Fnclex)
			INSTRUCTION_ENTRY0(Fninit)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			FP_8_STD_COLS(Fucomi)
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_STD_COLS(Fcomi)
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x03)

	BEGIN_INSTRUCTION_ROW(0x04) /*  DC */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_REV_COLS(Fadd)
			FP_8_REV_COLS(Fmul)
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_BLANK_COLS()
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			FP_8_REV_COLS(Fsubr)
			FP_8_REV_COLS(Fsub)
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_REV_COLS(Fdivr)
			FP_8_REV_COLS(Fdiv)
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x04)

	BEGIN_INSTRUCTION_ROW(0x05) /*  DD */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_STD_COLS_SINGLE(Ffree)
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_STD_COLS_SINGLE(Fst)
			FP_8_STD_COLS_SINGLE(Fstp)
		END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			FP_8_STD_COLS_SINGLE(Fucom)
			FP_8_STD_COLS_SINGLE(Fucomp)
		END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_BLANK_COLS()
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x05)

	BEGIN_INSTRUCTION_ROW(0x06) /*  DE */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_REV_COLS(Faddp)
			FP_8_REV_COLS(Fmulp)
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_BLANK_COLS()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY0(Fcompp)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
        END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			FP_8_REV_COLS(Fsubrp)
			FP_8_REV_COLS(Fsubp)
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_REV_COLS(Fdivrp)
			FP_8_REV_COLS(Fdivp)
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x06)

	BEGIN_INSTRUCTION_ROW(0x07) /*  DF */
		BEGIN_INSTRUCTION_ROW(0x00)
			FP_8_BLANK_COLS()
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x00)
		BEGIN_INSTRUCTION_ROW(0x01)
			FP_8_BLANK_COLS()
			FP_8_BLANK_COLS()
		END_INSTRUCTION_ROW(0x01)
		BEGIN_INSTRUCTION_ROW(0x02)
			INSTRUCTION_ENTRY1(Fnstsw,AX)
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			INSTRUCTION_ENTRY_BLANK()
			FP_8_STD_COLS(Fucomip)
        END_INSTRUCTION_ROW(0x02)
		BEGIN_INSTRUCTION_ROW(0x03)
			FP_8_STD_COLS(Fcomip)
			FP_8_BLANK_COLS()
        END_INSTRUCTION_ROW(0x03)
	END_INSTRUCTION_ROW(0x07)
END_INSTRUCTION_TABLE


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


/*
typedef struct tagOPER_SIZE_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION ti16bit;
	TABLE_INSTRUCTION ti32bit;
}OPER_SIZE_DEP_INS_ENTRY,*POPER_SIZE_DEP_INS_ENTRY;*/


OPER_SIZE_DEP_INS_ENTRY oper_size_dep_ins_map[] = 
{
	{MneCbwOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Cbw,cbw)
		INSTRUCTION_ENTRY0_SZ(Cbw,cwde)},

	{MneCwdOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Cwd,cwd)
		INSTRUCTION_ENTRY0_SZ(Cwd,cdq)},

	{MnePushfOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Pushf,pushf)
		INSTRUCTION_ENTRY0_SZ(Pushf,pushfd)},

	{MnePopfOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Popf,popf)
		INSTRUCTION_ENTRY0_SZ(Popf,popfd)},

	{MneMovsOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Movs,movsw)
		INSTRUCTION_ENTRY0_SZ(Movs,movsd)},

	{MneCmpsOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Cmps,cmpsw)
		INSTRUCTION_ENTRY0_SZ(Cmps,cmpsd)},

	{MneStosOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Stos,stosw)
		INSTRUCTION_ENTRY0_SZ(Stos,stosd)},

	{MneLodsOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Lods,lodsw)
		INSTRUCTION_ENTRY0_SZ(Lods,lodsd)},

	{MneScasOperSizeDep,	
		INSTRUCTION_ENTRY0_SZ(Scas,scasw)
		INSTRUCTION_ENTRY0_SZ(Scas,scasd)},
};


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/

			
/*

typedef struct tagADDR_SIZE_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION ti16bit;
	TABLE_INSTRUCTION ti32bit;
}ADDR_SIZE_DEP_INS_ENTRY,*PADDR_SIZE_DEP_INS_ENTRY; 
*/

ADDR_SIZE_DEP_INS_ENTRY addr_size_dep_ins_map[] = 
{
	{MneJcxzAddrSizeDep,
				INSTRUCTION_ENTRY1_SZ(Jcxz,jcxz,Jb)
				INSTRUCTION_ENTRY1_SZ(Jcxz,jecxz,Jb)},
};


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


/*
typedef struct tagMOD_IS_3_DEP_INS_ENTRY
{
	MnemonicEnum mne;
	TABLE_INSTRUCTION tiModIs3;
	TABLE_INSTRUCTION tiModIsNot3;
}MOD_IS_3_DEP_INS_ENTRY,*PMOD_IS_3_DEP_INS_ENTRY;
*/

MOD_IS_3_DEP_INS_ENTRY mod_is_3_dep_ins_map[] = 
{
	{MneLFenceModLookup,
				INSTRUCTION_ENTRY0(Lfence)
				INSTRUCTION_ENTRY_BLANK()},
	{MneMFenceModLookup,
				INSTRUCTION_ENTRY0(Mfence)
				INSTRUCTION_ENTRY_BLANK()},
	{MneSFenceModLookup,
				INSTRUCTION_ENTRY0(Sfence)
				INSTRUCTION_ENTRY1(Clflush,MbWithPtrSizePrefix)},
	{MneMovlpsMovhlpsLookup,
				INSTRUCTION_ENTRY2(Movhlps,Vq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movlps,Vq,WqWithPtrSizePrefix)},    
	{MneMovhpsMovlhpsLookup,
				INSTRUCTION_ENTRY2(Movlhps,Vq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movhps,Vq,WqWithPtrSizePrefix)},    
};


/*******************************************************************/
/*******************************************************************/
/*******************************************************************/


/*
	TABLE_INSTRUCTION tiNoPrefix;
	TABLE_INSTRUCTION ti66;
	TABLE_INSTRUCTION tiF2;
	TABLE_INSTRUCTION tiF3;
*/

PREFIX_DEP_INS_ENTRY prefix_dep_ins_map[] =
{
	{MnePrefixDep_0F10,
				INSTRUCTION_ENTRY2(Movups,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movupd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movss,Vss,WssWithPtrSizePrefix)
	},
	{MnePrefixDep_0F11,
				INSTRUCTION_ENTRY2(Movups,WpsWithPtrSizePrefix,Vps)
				INSTRUCTION_ENTRY2(Movupd,WpdWithPtrSizePrefix,Vpd)
				INSTRUCTION_ENTRY2(Movsd,WsdWithPtrSizePrefix,Vsd)
				INSTRUCTION_ENTRY2(Movss,WssWithPtrSizePrefix,Vss)
	},
	{MnePrefixDep_0F12,
				INSTRUCTION_ENTRY0_MOD_LOOKUP_NEEDED(MovlpsMovhlpsLookup)
				INSTRUCTION_ENTRY2(Movlpd,Vq,WsWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
	},
	{MnePrefixDep_0F13,
				INSTRUCTION_ENTRY2(Movlps, WqWithPtrSizePrefix,Vq)
				INSTRUCTION_ENTRY2(Movlpd, WqWithPtrSizePrefix,Vq)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
	},
	{MnePrefixDep_0F14,
				INSTRUCTION_ENTRY2(Unpcklps,Vps,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Unpcklpd,Vpd,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
	},
	{MnePrefixDep_0F15,
				INSTRUCTION_ENTRY2(Unpckhps,Vps,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Unpckhpd,Vpd,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
	},
	{MnePrefixDep_0F16,
				INSTRUCTION_ENTRY0_MOD_LOOKUP_NEEDED(MovhpsMovlhpsLookup)
				INSTRUCTION_ENTRY2(Movhpd,Vq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
	},
	{MnePrefixDep_0F17,
				INSTRUCTION_ENTRY2(Movhps,WqWithPtrSizePrefix,Vq)
				INSTRUCTION_ENTRY2(Movhpd,WqWithPtrSizePrefix,Vq)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F28,
				INSTRUCTION_ENTRY2(Movaps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movapd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F29,
				INSTRUCTION_ENTRY2(Movaps,WpsWithPtrSizePrefix,Vps)
				INSTRUCTION_ENTRY2(Movapd,WpdWithPtrSizePrefix,Vpd)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F2A,
				INSTRUCTION_ENTRY2(Cvtpi2ps,Vps,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtpi2pd,Vpd,QdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtsi2sd,Vsd,EdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtsi2ss,Vss,EdWithPtrSizePrefix)},
	{MnePrefixDep_0F2B,
				INSTRUCTION_ENTRY2(Movntps,WpsWithPtrSizePrefix,Vps)
				INSTRUCTION_ENTRY2(Movntpd,WpdWithPtrSizePrefix,Vpd)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F2C,
				INSTRUCTION_ENTRY2(Cvttps2pi,Pq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvttpd2pi,Pq,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvttsd2si,Gd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvttss2si,Gd,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F2D,
				INSTRUCTION_ENTRY2(Cvtps2pi,Pq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtpd2pi,Pq,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtsd2si,Gd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtss2si,Gd,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F2E,
				INSTRUCTION_ENTRY2(Ucomiss,Vss,WdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Ucomisd,Vsd,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F2F,
				INSTRUCTION_ENTRY2(Comiss,Vps,WdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Comisd,Vsd,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F50,
				INSTRUCTION_ENTRY2(Movmskps,Ed,Vps)
				INSTRUCTION_ENTRY2(Movmskpd,Ed,Vpd)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F51,
				INSTRUCTION_ENTRY2(Sqrtps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Sqrtpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Sqrtsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Sqrtss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F52,
				INSTRUCTION_ENTRY2(Rsqrtps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Rsqrtss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F53,
				INSTRUCTION_ENTRY2(Rcpps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Rcpss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F54,
				INSTRUCTION_ENTRY2(Andps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Andpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F55,
				INSTRUCTION_ENTRY2(Andnps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Andnpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F56,
				INSTRUCTION_ENTRY2(Orps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Orpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F57,
				INSTRUCTION_ENTRY2(Xorps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Xorpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F58,
				INSTRUCTION_ENTRY2(Addps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Addpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Addsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Addss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F59,
				INSTRUCTION_ENTRY2(Mulps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Mulpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Mulsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Mulss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F5A,				
				INSTRUCTION_ENTRY2(Cvtps2pd,Vps,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtpd2ps,Vps,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtsd2ss,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtss2sd,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F5B,
				INSTRUCTION_ENTRY2(Cvtdq2ps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtps2dq,Vdq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Cvttps2dq,Vdq,WpsWithPtrSizePrefix)},
	{MnePrefixDep_0F5C,
				INSTRUCTION_ENTRY2(Subps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Subpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Subsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Subss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F5D,
				INSTRUCTION_ENTRY2(Minps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Minpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Minsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Minss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F5E,
				INSTRUCTION_ENTRY2(Divps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Divpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Divsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Divss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F5F,
				INSTRUCTION_ENTRY2(Maxps,Vps,WpsWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Maxpd,Vpd,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Maxsd,Vsd,WsdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Maxss,Vss,WssWithPtrSizePrefix)},
	{MnePrefixDep_0F60,
				INSTRUCTION_ENTRY2(Punpcklbw,Pq,QdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Punpcklbw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F61,
				INSTRUCTION_ENTRY2(Punpcklwd,Pq,QdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Punpcklwd,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F62,
				INSTRUCTION_ENTRY2(Punpckldq,Pq,QdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Punpckldq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F63,
				INSTRUCTION_ENTRY2(Packsswb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Packsswb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F64,
				INSTRUCTION_ENTRY2(Pcmpgtb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pcmpgtb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F65,
				INSTRUCTION_ENTRY2(Pcmpgtw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pcmpgtw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F66,
				INSTRUCTION_ENTRY2(Pcmpgtd,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pcmpgtd,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F67,
				INSTRUCTION_ENTRY2(Packuswb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Packuswb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F68,
				INSTRUCTION_ENTRY2(Punpckhbw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Punpckhbw,Pdq,QdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F69,
				INSTRUCTION_ENTRY2(Punpckhwd,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Punpckhwd,Pdq,QdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F6A,
				INSTRUCTION_ENTRY2(Punpckhdq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Punpckhdq,Pdq,QdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F6B,
				INSTRUCTION_ENTRY2(Packssdw,Pq,QdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Packssdw,Pdq,QdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F6C,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Punpcklqdq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F6D,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Punpckhqdq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F6E,
				INSTRUCTION_ENTRY2(Movd,Pd,EdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movd,Vdq,EdWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F6F,
				INSTRUCTION_ENTRY2(Movq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movdqa,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Movdqu,Vdq,WdqWithPtrSizePrefix)},
	{MnePrefixDep_0F70,
				INSTRUCTION_ENTRY3(Pshufw,Pq,QqWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Pshufd,Vdq,WdqWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Pshuflw,Vdq,WdqWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Pshufhw,Vdq,WdqWithPtrSizePrefix,Ib)},
	{MnePrefixDep_0F71,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F72,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F73,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F74,
				INSTRUCTION_ENTRY2(Pcmpeqb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pcmpeqb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F75,
				INSTRUCTION_ENTRY2(Pcmpeqw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pcmpeqw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F76,
				INSTRUCTION_ENTRY2(Pcmpeqd,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pcmpeqd,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F7E,
				INSTRUCTION_ENTRY2(Movd,EdWithPtrSizePrefix,Pd)
				INSTRUCTION_ENTRY2(Movd,EdWithPtrSizePrefix,Vdq)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Movq,Vq,WqWithPtrSizePrefix)},
	{MnePrefixDep_0F7F,
				INSTRUCTION_ENTRY2(Movq,QqWithPtrSizePrefix,Pq)
				INSTRUCTION_ENTRY2(Movdqa,WdqWithPtrSizePrefix,Vdq)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Movdqu,WdqWithPtrSizePrefix,Vdq)},
	{MnePrefixDep_0FC2,
				INSTRUCTION_ENTRY3(Cmpss,Vps,WpsWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Cmppd,Vpd,WpdWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Cmpsd,Vsd,WsdWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Cmpss,Vss,WssWithPtrSizePrefix,Ib)},
	{MnePrefixDep_0FC4,
				INSTRUCTION_ENTRY3(Pinsrw,Pq,EwWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Pinsrw,Vdq,EwWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FC5,
				INSTRUCTION_ENTRY3(Pextrw,Gd,Qq,Ib)
				INSTRUCTION_ENTRY3(Pextrw,Gd,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FC6,
				INSTRUCTION_ENTRY3(Shufps,Vps,WpsWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY3(Shufpd,Vpd,WpdWithPtrSizePrefix,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD1,
				INSTRUCTION_ENTRY2(Psrlw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psrlw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD2,
				INSTRUCTION_ENTRY2(Psrld,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psrld,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD3,
				INSTRUCTION_ENTRY2(Psrlq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psrlq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD4,
				INSTRUCTION_ENTRY2(Paddq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD5,
				INSTRUCTION_ENTRY2(Pmullw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmullw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD6,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Movq,WqWithPtrSizePrefix,Vq)
				INSTRUCTION_ENTRY2(Movdq2q,Pq,WqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Movq2dq,Vdq,QqWithPtrSizePrefix)},
	{MnePrefixDep_0FD7,
				INSTRUCTION_ENTRY2(Pmovmskb,Gd,Qq)
				INSTRUCTION_ENTRY2(Pmovmskb,Gd,Wdq)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD8,
				INSTRUCTION_ENTRY2(Psubusb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubusb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FD9,
				INSTRUCTION_ENTRY2(Psubusw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubusw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FDA,
				INSTRUCTION_ENTRY2(Pminub,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pminub,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FDB,
				INSTRUCTION_ENTRY2(Pand,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pand,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FDC,
				INSTRUCTION_ENTRY2(Paddusb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddusb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FDD,
				INSTRUCTION_ENTRY2(Paddusw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddusw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FDE,
				INSTRUCTION_ENTRY2(Pmaxub,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmaxub,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FDF,
				INSTRUCTION_ENTRY2(Pandn,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pandn,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE0,
				INSTRUCTION_ENTRY2(Pavgb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pavgb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE1,
				INSTRUCTION_ENTRY2(Psraw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psraw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE2,
				INSTRUCTION_ENTRY2(Psrad,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psrad,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE3,
				INSTRUCTION_ENTRY2(Pavgw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pavgw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE4,
				INSTRUCTION_ENTRY2(Pmulhuw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmulhuw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE5,
				INSTRUCTION_ENTRY2(Pmulhw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmulhw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE6,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Cvttpd2dq,Vdq,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtpd2dq,Vdq,WpdWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Cvtdq2pd,Vpd,WdqWithPtrSizePrefix)},
	{MnePrefixDep_0FE7,
				INSTRUCTION_ENTRY2(Movntq,WqWithPtrSizePrefix,Pq)
				INSTRUCTION_ENTRY2(Movntdq,WdqWithPtrSizePrefix,Vdq)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE8,
				INSTRUCTION_ENTRY2(Psubsb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubsb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FE9,
				INSTRUCTION_ENTRY2(Psubsw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubsw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FEA,
				INSTRUCTION_ENTRY2(Pminsw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pminsw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FEB,
				INSTRUCTION_ENTRY2(Por,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Por,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FEC,
				INSTRUCTION_ENTRY2(Paddsb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddsb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FED,
				INSTRUCTION_ENTRY2(Paddsw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddsw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FEE,
				INSTRUCTION_ENTRY2(Pmaxsw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmaxsw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FEF,
				INSTRUCTION_ENTRY2(Pxor,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pxor,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF1,
				INSTRUCTION_ENTRY2(Psllw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psllw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF2,
				INSTRUCTION_ENTRY2(Pslld,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pslld,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF3,
				INSTRUCTION_ENTRY2(Psllq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psllq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF4,
				INSTRUCTION_ENTRY2(Pmuludq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmuludq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF5,
				INSTRUCTION_ENTRY2(Pmaddwd,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Pmaddwd,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF6,
				INSTRUCTION_ENTRY2(Psadbw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psadbw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF7,
				INSTRUCTION_ENTRY2(Maskmovq,Ppi,QpiWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Maskmovdqu,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF8,
				INSTRUCTION_ENTRY2(Psubb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FF9,
				INSTRUCTION_ENTRY2(Psubw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FFA,
				INSTRUCTION_ENTRY2(Psubd,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubd,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FFB,
				INSTRUCTION_ENTRY2(Psubq,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Psubq,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FFC,
				INSTRUCTION_ENTRY2(Paddb,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddb,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FFD,
				INSTRUCTION_ENTRY2(Paddw,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddw,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0FFE,
				INSTRUCTION_ENTRY2(Paddd,Pq,QqWithPtrSizePrefix)
				INSTRUCTION_ENTRY2(Paddd,Vdq,WdqWithPtrSizePrefix)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},

	
	{MnePrefixDep_0F71_B_2,
				INSTRUCTION_ENTRY2(Psrlw,Qq,Ib)
				INSTRUCTION_ENTRY2(Psrlw,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F71_B_4,
				INSTRUCTION_ENTRY2(Psraw,Qq,Ib)
				INSTRUCTION_ENTRY2(Psraw,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F71_B_6,
				INSTRUCTION_ENTRY2(Psllw,Qq,Ib)
				INSTRUCTION_ENTRY2(Psllw,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},

	{MnePrefixDep_0F72_C_2,
				INSTRUCTION_ENTRY2(Psrld,Qq,Ib)
				INSTRUCTION_ENTRY2(Psrld,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F72_C_4,
				INSTRUCTION_ENTRY2(Psrad,Qq,Ib)
				INSTRUCTION_ENTRY2(Psrad,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F72_C_6,
				INSTRUCTION_ENTRY2(Pslld,Qq,Ib)
				INSTRUCTION_ENTRY2(Pslld,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},

	{MnePrefixDep_0F73_D_2,
				INSTRUCTION_ENTRY2(Psrlq,Qq,Ib)
				INSTRUCTION_ENTRY2(Psrlq,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F73_D_3,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Psrldq,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F73_D_6,
				INSTRUCTION_ENTRY2(Psllq,Qq,Ib)
				INSTRUCTION_ENTRY2(Psllq,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
	{MnePrefixDep_0F73_D_7,
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY2(Pslldq,Wdq,Ib)
				INSTRUCTION_ENTRY_BLANK()
				INSTRUCTION_ENTRY_BLANK()},
};

/*******************************************************************/

#define SIZEOF_OPER_SIZE_DEP_INS_MAP	\
			(SIZEOF_TABLE(oper_size_dep_ins_map))
#define SIZEOF_ADDR_SIZE_DEP_INS_MAP	\
			(SIZEOF_TABLE(addr_size_dep_ins_map))
#define SIZEOF_PREFIX_DEP_INS_MAP		\
			(SIZEOF_TABLE(prefix_dep_ins_map))
#define SIZEOF_MOD_IS_3_DEP_MAP			\
			(SIZEOF_TABLE(mod_is_3_dep_ins_map))

/*******************************************************************/